// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGF20RIQgLit18GrYFY7ZbrQNR7TWfLU4',
    appId: '1:779307743834:web:ce8815939df6430a8cf663',
    messagingSenderId: '779307743834',
    projectId: 'oc-quiz-for-fun-53309',
    authDomain: 'oc-quiz-for-fun-53309.firebaseapp.com',
    storageBucket: 'oc-quiz-for-fun-53309.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDniELdObQ1CG-GKe4JyIduh6wDgVKygm8',
    appId: '1:779307743834:android:24c418ca4007c90c8cf663',
    messagingSenderId: '779307743834',
    projectId: 'oc-quiz-for-fun-53309',
    storageBucket: 'oc-quiz-for-fun-53309.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8L08Zn0sLSh7krHMiHJVH0_-MLu74t0c',
    appId: '1:779307743834:ios:4f3e3bbb1f54ed248cf663',
    messagingSenderId: '779307743834',
    projectId: 'oc-quiz-for-fun-53309',
    storageBucket: 'oc-quiz-for-fun-53309.appspot.com',
    iosClientId: '779307743834-bqrcge5m288cg5568jlbuofv6f2fn6p4.apps.googleusercontent.com',
    iosBundleId: 'com.example.ocQuizForFun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8L08Zn0sLSh7krHMiHJVH0_-MLu74t0c',
    appId: '1:779307743834:ios:4f3e3bbb1f54ed248cf663',
    messagingSenderId: '779307743834',
    projectId: 'oc-quiz-for-fun-53309',
    storageBucket: 'oc-quiz-for-fun-53309.appspot.com',
    iosClientId: '779307743834-bqrcge5m288cg5568jlbuofv6f2fn6p4.apps.googleusercontent.com',
    iosBundleId: 'com.example.ocQuizForFun',
  );
}
